<?php
$verbosIrregulares = array(
    array("ser", "be", "was / were", "been"),
    array("tener", "have", "had", "had"),
    array("hacer", "do", "did", "done"),
    array("decir", "say", "said", "said"),
    array("ir", "go", "went", "gone"),
    array("poder", "can", "could", "been able"),
    array("ver", "see", "saw", "seen"),
    array("obtener", "get", "got", "gotten / got"),
    array("hacer", "make", "made", "made"),
    array("saber", "know", "knew", "known"),
    array("pensar", "think", "thought", "thought"),
    array("tomar", "take", "took", "taken"),
    array("ver", "see", "saw", "seen"),
    array("venir", "come", "came", "come"),
    array("dar", "give", "gave", "given"),
    array("decir", "tell", "told", "told"),
    array("trabajar", "work", "worked / wrought", "worked / wrought"),
    array("necesitar", "need", "needed", "needed"),
    array("sentir", "feel", "felt", "felt"),
    array("poner", "put", "put", "put"),
    array("significar", "mean", "meant", "meant"),
    array("guardar", "keep", "kept", "kept"),
    array("dejar", "let", "let", "let"),
    array("empezar", "begin", "began", "begun"),
    array("parecer", "seem", "seemed", "seemed"),
    array("ayudar", "help", "helped", "helped"),
    array("hablar", "speak", "spoke", "spoken"),
    array("girar", "turn", "turned", "turned"),
    array("mostrar", "show", "showed", "shown"),
    array("oír", "hear", "heard", "heard"),
    array("jugar", "play", "played", "played"),
    array("correr", "run", "ran", "run"),
    array("mover", "move", "moved", "moved"),
    array("vivir", "live", "lived", "lived"),
    array("creer", "believe", "believed", "believed"),
    array("llevar", "wear", "wore", "worn"),
    array("ganar", "win", "won", "won"),
    array("escribir", "write", "wrote", "written"),
    array("perder", "lose", "lost", "lost"),
    array("escoger", "choose", "chose", "chosen"),
    array("caer", "fall", "fell", "fallen"),
    array("enviar", "send", "sent", "sent"),
    array("construir", "build", "built", "built"),
    array("entender", "understand", "understood", "understood"),
    array("romper", "break", "broke", "broken"),
    array("crecer", "grow", "grew", "grown"),
    array("dividir", "split", "split", "split"),
    array("pagar", "pay", "paid", "paid"),
    array("satisfacer", "meet", "met", "met"),
    array("correr", "read", "read", "read"),
    array("comer", "eat", "ate", "eaten"),
    array("caer", "fall", "fell", "fallen"),
    array("dirigir", "lead", "led", "led"),
    array("comprender", "read", "read", "read"),
    array("nadar", "swim", "swam", "swum"),
    array("cubrir", "cover", "covered", "covered"),
    array("desarrollar", "build", "built", "built"),
    array("cambiar", "change", "changed", "changed"),
    array("escuchar", "hear", "heard", "heard"),
    array("trabajar", "work", "worked / wrought", "worked / wrought"),
    array("jugar", "play", "played", "played"),
    array("terminar", "finish", "finished", "finished"),
    array("caminar", "walk", "walked", "walked"),
    array("subir", "climb", "climbed", "climbed"),
    array("darse cuenta", "realize", "realized", "realized"),
    array("ganar", "win", "won", "won"),
    array("saber", "know", "knew", "known"),
    array("entender", "understand", "understood", "understood"),
    array("vivir", "live", "lived", "lived"),
    array("morir", "die", "died", "died"),
    array("perder", "lose", "lost", "lost"),
    array("buscar", "seek", "sought", "sought"),
    array("encontrar", "find", "found", "found"),
    array("coger", "catch", "caught", "caught"),
    array("llegar", "arrive", "arrived", "arrived"),
    array("preparar", "prepare", "prepared", "prepared"),
    array("creer", "believe", "believed", "believed"),
    array("decidir", "decide", "decided", "decided"),
    array("decir", "tell", "told", "told"),
    array("mostrar", "show", "showed", "shown"),
    array("escribir", "write", "wrote", "written"),
    array("comer", "eat", "ate", "eaten"),
    array("cambiar", "change", "changed", "changed"),
    array("comenzar", "begin", "began", "begun"),
    array("entender", "understand", "understood", "understood"),
    array("pensar", "think", "thought", "thought"),
    array("tomar", "take", "took", "taken"),
    array("perder", "lose", "lost", "lost"),
    array("escuchar", "hear", "heard", "heard"),
    array("llegar", "arrive", "arrived", "arrived"),
    array("correr", "run", "ran", "run"),
    array("saber", "know", "knew", "known"),
    array("hablar", "speak", "spoke", "spoken"),
    array("nadar", "swim", "swam", "swum"),
    array("dar", "give", "gave", "given"),
    array("ver", "see", "saw", "seen"),
    array("parecer", "seem", "seemed", "seemed"),
    array("oír", "hear", "heard", "heard"),
    array("cubrir", "cover", "covered", "covered"),
    array("sentir", "feel", "felt", "felt"),
    array("coger", "catch", "caught", "caught"),
    array("preparar", "prepare", "prepared", "prepared"),
    array("buscar", "seek", "sought", "sought"),
    array("encontrar", "find", "found", "found"),
    array("llevar", "wear", "wore", "worn"),
    array("salir", "go out", "went out", "gone out"),
    array("dejar", "leave", "left", "left"),
    array("saber", "know", "knew", "known"),
    array("volver", "return", "returned", "returned"),
    array("crear", "create", "created", "created"),
    array("caer", "fall", "fell", "fallen"),
    array("entender", "understand", "understood", "understood"),
    array("dejar", "let", "let", "let"),
    array("reconocer", "recognize", "recognized", "recognized"),
    array("sentarse", "sit", "sat", "sat"),
    array("oír", "hear", "heard", "heard"),
    array("caer", "fall", "fell", "fallen"),
    array("volar", "fly", "flew", "flown"),
    array("suceder", "happen", "happened", "happened"),
    array("conseguir", "get", "got", "gotten / got"),
    array("salir", "go", "went", "gone"),
    array("dirigir", "lead", "led", "led"),
    array("sentir", "feel", "felt", "felt"),
    array("construir", "build", "built", "built"),
    array("perder", "lose", "lost", "lost"),
    array("dejar", "let", "let", "let"),
    array("mostrar", "show", "showed", "shown"),
    array("escoger", "choose", "chose", "chosen"),
    array("decidir", "decide", "decided", "decided"),
    array("permanecer", "stay", "stayed", "stayed"),
    array("alcanzar", "reach", "reached", "reached"),
    array("crear", "create", "created", "created"),
    array("trabajar", "work", "worked / wrought", "worked / wrought"),
    array("correr", "run", "ran", "run"),
    array("recibir", "receive", "received", "received"),
    array("dejar", "leave", "left", "left"),
    array("producir", "produce", "produced", "produced"),
    array("comer", "eat", "ate", "eaten"),
    array("saber", "know", "knew", "known"),
    array("llevar", "wear", "wore", "worn"),
    array("hablar", "speak", "spoke", "spoken"),
    array("nadar", "swim", "swam", "swum"),
    array("dar", "give", "gave", "given"),
    array("encontrar", "find", "found", "found"),
    array("decir", "say", "said", "said"),
    array("llevar puesto", "put on", "put on", "put on"),
    array("sentar", "set", "set", "set"),
    array("soltar", "let go", "let go", "let go"),
    array("descubrir", "discover", "discovered", "discovered"),
    array("oír", "hear", "heard", "heard"),
    array("sentirse", "feel", "felt", "felt"),
    array("volar", "fly", "flew", "flown"),
    array("pasar tiempo", "spend time", "spent time", "spent time"),
    array("vivir", "live", "lived", "lived"),
    array("sentir", "feel", "felt", "felt"),
    array("coger", "catch", "caught", "caught"),
    array("tener éxito", "succeed", "succeeded", "succeeded"),
    array("poner", "put", "put", "put"),
    array("quedarse", "stay", "stayed", "stayed"),
    array("continuar", "continue", "continued", "continued"),
    array("volver", "return", "returned", "returned"),
    array("golpear", "hit", "hit", "hit"),
    array("reconocer", "recognize", "recognized", "recognized"),
    array("levantar", "lift", "lifted", "lifted"),
    array("cambiar", "change", "changed", "changed"),
    array("creer", "believe", "believed", "believed"),
    array("parar", "stop", "stopped", "stopped"),
    array("usar", "wear", "wore", "worn"),
    array("encontrar", "find", "found", "found"),
    array("ayudar", "help", "helped", "helped"),
    array("empezar", "begin", "began", "begun"),
    array("pasar tiempo", "spend time", "spent time", "spent time"),
    array("construir", "build", "built", "built"),
    array("olvidar", "forget", "forgot", "forgotten"),
    array("recordar", "remember", "remembered", "remembered"),
    array("llorar", "cry", "cried", "cried"),
    array("mover", "move", "moved", "moved"),
    array("despertar", "wake", "woke", "woken"),
    array("mostrar", "show", "showed", "shown"),
    array("matar", "kill", "killed", "killed"),
    array("viajar", "travel", "traveled / travelled", "traveled / travelled"),
    array("navegar", "sail", "sailed", "sailed"),
    array("ver", "see", "saw", "seen"),
    array("mostrar", "show", "showed", "shown"),
    array("pagar", "pay", "paid", "paid"),
    array("cerrar", "shut", "shut", "shut"),
    array("oler", "smell", "smelled / smelt", "smelled / smelt"),
    array("vender", "sell", "sold", "sold"),
    array("empezar", "begin", "began", "begun"),
    array("tener", "have", "had", "had"),
    array("poder", "can", "could", "been able"),
    array("pensar", "think", "thought", "thought"),
    array("decir", "tell", "told", "told"),
    array("cortar", "cut", "cut", "cut"),
    array("partir", "split", "split", "split"),
    array("caer", "fall", "fell", "fallen"),
    array("volcar", "spill", "spilled / spilt", "spilled / spilt"),
    array("gastar", "spend", "spent", "spent"),
    array("dividir", "split", "split", "split"),
    array("gritar", "shout", "shouted", "shouted"),
    array("correr", "run", "ran", "run"),
    array("sentar", "sit", "sat", "sat"),
    array("llegar", "arrive", "arrived", "arrived"),
    array("aprender", "learn", "learned / learnt", "learned / learnt"),
    array("crecer", "grow", "grew", "grown"),
    array("coger", "catch", "caught", "caught"),
    array("comer", "eat", "ate", "eaten"),
    array("vivir", "live", "lived", "lived"),
    array("llevar", "wear", "wore", "worn")
);